halflife.wad
liquids.wad
tfc.wad
models/christmas/santa.mdl
models/christmas/snowman.mdl
models/christmas/tree.mdl
models/backpack.mdl
models/barnacle.mdl
models/flag.mdl
models/homer.mdl
models/invis.mdl
models/islave.mdl
sound/aslave/slv_word4.wav
sound/barnacle/bcl_die1.wav
sound/christmas/hohoho.wav
sound/christmas/iamsantaclause.wav
sound/misc/r_tele2.wav
sound/misc/woohoo.wav
sound/weapons/scock1.wav
sprites/flare1.spr
